# Python data analysis

In [45]:
import numpy as np
import pandas as pd
import glob
import os

In [87]:
 # make your own path to the data
path='/Users/alessandralupini/Downloads/Project_PythonDataIES-master/First_q/'
csv_path=path+"*.csv"
files=glob.glob(csv_path)      # gives you list of csv files in the directory

files=sorted(files)

In [70]:
files=sorted(files)

In [148]:
first_q= [pd.read_csv(file) for file in files]

In [89]:
# make your own path to the data
path2='/Users/alessandralupini/Downloads/Project_PythonDataIES-master/second_q/'
csv_path2=path2+"*.csv"
files2=glob.glob(csv_path2)     # gives you list of csv files in the directory
files2=sorted(files2)

In [121]:
Second_q= [pd.read_csv(file) for file in files2]

In [122]:
# make your own path to the data
path3='/Users/alessandralupini/Downloads/Project_PythonDataIES-master/Third_q/'
csv_path3=path3+"*.csv"
files3=glob.glob(csv_path3)     # gives you list of csv files in the directory
files3=sorted(files3)

In [123]:
Third_q= [pd.read_csv(file) for file in files3]

In [124]:
# make your own path to the data
path4='/Users/alessandralupini/Downloads/Project_PythonDataIES-master/Fourth_q/'
csv_path4=path4+"*.csv"
files4=glob.glob(csv_path4)     # gives you list of csv files in the directory
files4=sorted(files4)

In [125]:
Fourth_q= [pd.read_csv(file) for file in files4]

In [156]:
for x in first_q: 
    x.columns=['city', 'year', 'month', 'day', 'mean T', 'min T', 'max T', 'prec', 'humidity', 'wind']

In [157]:
for x in Second_q: 
    x.columns=['city', 'year', 'month', 'day', 'mean T', 'min T', 'max T', 'prec', 'humidity', 'wind']

In [158]:
for x in Third_q: 
    x.columns=['city', 'year', 'month', 'day', 'mean T', 'min T', 'max T', 'prec', 'humidity', 'wind']

In [159]:
for x in Fourth_q: 
    x.columns=['city', 'year', 'month', 'day', 'mean T', 'min T', 'max T', 'prec', 'humidity', 'wind']

In [154]:
len(Third_q)

1820

In [ ]:
for

In [221]:
#Second_q[6].iloc[:,7] = Second_q[6].iloc[:,7].replace(" ", np.NaN)
#Second_q[6].iloc[:,7] = Second_q[6].iloc[:,7].replace("   ", np.NaN)


Second_q[6]

    city  year   month  day  mean T  min T  max T  prec  humidity  wind
0   Bari  1991  Aprile    1    10.6    6.7   14.9   0.0        66  29.4
1   Bari  1991  Aprile    2    10.5    7.0   15.1   0.0        68  22.2
2   Bari  1991  Aprile    3    11.1    6.3   16.3   0.0        72  14.8
3   Bari  1991  Aprile    4    11.8    5.4   18.8   0.0        77  22.2
4   Bari  1991  Aprile    5    13.7    5.6   20.1   1.0        70  25.9
5   Bari  1991  Aprile    6    12.1    9.0   15.1   4.0        85  31.7
6   Bari  1991  Aprile    7    14.1    8.7   19.7   0.0        69  27.8
7   Bari  1991  Aprile    8    14.3   11.0   19.0   0.0        65  20.6
8   Bari  1991  Aprile    9    13.8    9.6   18.7   0.0        63  33.5
9   Bari  1991  Aprile   10    13.3    8.8   18.0   0.0        62  24.1
10  Bari  1991  Aprile   11     8.4    6.0   12.0   9.0        85  31.3
11  Bari  1991  Aprile   12     8.9    5.8   13.0  23.0        85  29.4
12  Bari  1991  Aprile   13     9.7    6.0   13.6   7.0        82  14.8
13  Bari  1991  Aprile   14    10.5    4.6   15.9   0.0        77  13.0
14  Bari  1991  Aprile   15    12.0    6.0   17.0   0.0        74  20.6
15  Bari  1991  Aprile   16    13.3    8.4   18.2   0.0        69  18.3
16  Bari  1991  Aprile   17    14.7   10.2   19.1   3.0        75  29.4
17  Bari  1991  Aprile   18    15.4   10.0   21.4   4.0        65  35.2
18  Bari  1991  Aprile   19    11.4    7.0   16.2   0.0        59  35.2
19  Bari  1991  Aprile   20    11.3    6.0   16.0   1.0        61  55.4
20  Bari  1991  Aprile   21     9.9    4.7   16.0   0.0        72  31.7
21  Bari  1991  Aprile   22     9.4    4.6   14.0   0.0        74  20.6
22  Bari  1991  Aprile   23     9.5    3.0   14.0   3.0        74  18.3
23  Bari  1991  Aprile   24     9.3    5.5   14.0   0.0        78  27.8
24  Bari  1991  Aprile   25    10.9    6.5   15.0   1.0        63  24.1
25  Bari  1991  Aprile   26    11.6    5.6   16.3   2.0        80  46.5
26  Bari  1991  Aprile   27    12.8    9.0   19.2   2.0        71  27.8
27  Bari  1991  Aprile   28    11.5    5.1   16.3   0.0        73  18.3
28  Bari  1991  Aprile   29    12.6    8.0   18.6   0.0        76  35.2
29  Bari  1991  Aprile   30    14.9   11.0   20.1   0.0        61  29.4
..   ...   ...     ...  ...     ...    ...    ...   ...       ...   ...
61  Bari  1991  Giugno    1    18.9   10.6   25.0   0.0        51  31.7
62  Bari  1991  Giugno    2    20.7   15.5   26.6   0.0        50  22.2
63  Bari  1991  Giugno    3    20.6   12.0   27.5   0.0        55  25.9
64  Bari  1991  Giugno    4    20.1   15.2   23.7   0.0        69  24.1
65  Bari  1991  Giugno    5    19.5   14.0   26.4   0.0        67  46.5
66  Bari  1991  Giugno    6    20.3   11.8   27.0   0.0        60  18.3
67  Bari  1991  Giugno    7    24.7   15.6   32.0   0.0        51  22.2
68  Bari  1991  Giugno    8    21.7   16.0   28.1   1.0        66  31.7
69  Bari  1991  Giugno    9    20.2   15.9   25.0   2.0        65  27.8
70  Bari  1991  Giugno   10    22.6   15.0   28.1   0.0        49  14.8
71  Bari  1991  Giugno   11    22.4   15.6   28.1   0.0        62  20.6
72  Bari  1991  Giugno   12    21.3   16.0   25.2   0.0        73  16.5
73  Bari  1991  Giugno   13    21.7   15.0   27.4   0.0        60  11.1
74  Bari  1991  Giugno   14    25.5   16.2   30.7   0.0        49  11.1
75  Bari  1991  Giugno   15    23.4   16.2   28.6   0.0        68   7.6
76  Bari  1991  Giugno   16    26.4   17.0   35.0   0.0        44  20.6
77  Bari  1991  Giugno   17    28.1   20.6   34.4   0.0        36  24.1
78  Bari  1991  Giugno   18    24.8   20.0   31.2   0.0        67  13.0
79  Bari  1991  Giugno   19    21.7   17.0   27.1   0.0        60  24.1
80  Bari  1991  Giugno   20    20.2   13.5   25.3   0.0        64  13.0
81  Bari  1991  Giugno   21    20.4   12.9   25.2   0.0        66  18.3
82  Bari  1991  Giugno   22    21.3   16.6   26.3   0.0        66  18.3
83  Bari  1991  Giugno   23    23.2   16.4   28.5   0.0        51  14.8
84  Bari  1991  Giugno   24    24.4   17.5   30.8   0.0        48  13.0
85  Bari  1991  Giugno   25    24.6   17.0   30.3   0.0        60  11.1
86  Bari  1991  Giugno   26    25.8   18.3   31.6   0.0        59  11.1
87  Bari  1991  Giugno   27    27.2   20.5   32.4   0.0        59  11.1
88  Bari  1991  Giugno   28    27.7   21.0   36.0   0.0        51  22.2
89  Bari  1991  Giugno   29    22.3   18.0   26.7   0.0        59  25.9
90  Bari  1991  Giugno   30    20.4   16.0   24.1   0.0        57  33.5

[91 rows x 10 columns]

In [218]:
Second_q[6].iloc[:,7]=Second_q[6].iloc[:,7].replace(np.NaN,0)

In [217]:
isNaN(Second_q[6].iloc[90,7])

NameError: name 'isNaN' is not defined

In [223]:
np.mean(Second_q[6].iloc[:,7])

1.1318681318681318

In [224]:
meansmean_T_first_q=[np.nanmean(x["mean T"]) for x in first_q]
meansmean_T_Second_q=[np.nanmean(x["mean T"]) for x in Second_q]
meansmean_T_Third_q=[np.nanmean(x["mean T"]) for x in Third_q]
meansmean_T_Fourth_q=[np.nanmean(x["mean T"]) for x in Fourth_q]

AttributeError: 'str' object has no attribute 'dtype'

In [225]:
meansprec_first_q=[np.mean(x["prec"]) for x in first_q]
meansprec_Second_q=[np.mean(x["prec"]) for x in Second_q]
meansprec_Third_q=[np.mean(x["prec"]) for x in Third_q]
meansprec_Fourth_q=[np.mean(x["prec"]) for x in Fourth_q]

TypeError: Could not convert 1.01.0   11.01.03.0         12.0    4.0       1.0 11.09.012.0                 1.02.032.0     1.01.02.0                    1.0     4.0   5.05.01.05.0 1.01.01.0    2.01.01.01.0 1.0      to numeric

In [226]:
meanswind_first_q=[np.mean(x["wind"]) for x in first_q]
meanswind_Second_q=[np.mean(x["wind"]) for x in Second_q]
meanswind_Third_q=[np.mean(x["wind"]) for x in Third_q]
meanswind_Fourth_q=[np.mean(x["wind"]) for x in Fourth_q]

TypeError: Could not convert 29.427.820.611.111.1 13.029.414.89.414.814.811.124.120.613.0 13.016.516.513.09.418.318.324.114.818.316.516.524.118.322.29.49.49.414.829.424.111.118.314.813.014.825.937.025.913.024.114.811.111.113.018.324.138.937.055.442.437.051.951.922.237.040.725.918.314.822.224.124.124.19.420.614.824.127.822.225.933.537.022.218.346.537.031.714.814.813.09.414.8 to numeric

In [227]:
#variance of mean T
varmean_T_first_q=[np.var(x["mean T"]) for x in first_q]
varmean_T_Second_q=[np.var(x["mean T"]) for x in Second_q]
varmean_T_Third_q=[np.var(x["mean T"]) for x in Third_q]
varmean_T_Fourth_q=[np.var(x["mean T"]) for x in Fourth_q]

TypeError: could not convert string to float:

In [ ]:
#variance prec
varprec_first_q=[np.var(x["prec"]) for x in first_q]
varprec_Second_q=[np.var(x["prec"]) for x in Second_q]
varprec_Third_q=[np.var(x["prec"]) for x in Third_q]
varprec_Fourth_q=[np.var(x["prec"]) for x in Fourth_q]

In [ ]:
#variance wind
varwind_first_q=[np.var(x["wind"]) for x in first_q]
varwind_Second_q=[np.var(x["wind"]) for x in Second_q]
varwind_Third_q=[np.var(x["wind"]) for x in Third_q]
varwind_Fourth_q=[np.var(x["wind"]) for x in Fourth_q]

In [128]:
np.mean(second_q[0][["T max"]])

T max    22.551648
dtype: float64

In [228]:
'''  Add a new column - difference between max and min temperature  '''
for table in first_q:
    table["T diff"]=table.iloc[:,6]-table.iloc[:,5]

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
path#[0:10]

In [ ]:
files[0:10]

NameError: name 'Second_q' is not defined