# ITA_weather project data processing

## In this part we upload dataframes of the scraped monthly tables, we delete unnecessary columns and we order them into 4 lists of quarterly dataframes. Then we transform values in our tables from strings to floats and replace missing values with np.NaNs. These quarterly dataframes are then exported into csv-files for the use in the next part of the project.

In [1]:
import numpy as np
import pandas as pd
import glob
import os

## Originally we made a mistake in naming of the csv files with tables, therefore the upload did not keep the correct ordering. Before project deadline those were the files available on GitHub, so when using those rearangement of ordering is neccessary.

In [2]:
path='d:\moje_dokumenty\Desktop\IES\semester 11\Python\project\DATA1\ '  # make your own path to the data
csv_path=path+"*.csv"
files=glob.glob(csv_path)      # gives you list of csv files in the directory, unfortunately sorted in a wrong way
#numbers=[i for i in range(len(files))]
#corrected_files=[files[i][:63]+str(numbers[i])+".csv" for i in range(len(files)) ]

In [3]:
list_of_DFs = [pd.read_csv(file) for file in  files]

In [4]:
path2='d:\moje_dokumenty\Desktop\IES\semester 11\Python\project\DATA02\ '  # make your own path to the data
csv_path2=path2+"*.csv"
files2=glob.glob(csv_path2)      # gives you list of csv files in the directory, unfortunately sorted in a wrong way
#numbers2=[i for i in range(len(files2))]
#corrected_files2=[files2[i][:64]+str(numbers2[i])+".csv" for i in range(len(files2)) ]

In [5]:
list_of_DFs2 = [pd.read_csv(file) for file in  files2]

In [6]:
#deleting columns which are not needed
col_to_del=["Raffica","Fenomeni","Info"]
for table in list_of_DFs:
    for x in col_to_del:
        del table[x]

for table in list_of_DFs2:
    for x in col_to_del:
        del table[x]

In [7]:
'''  For making computation faster, first let join appropriate months into quarters  '''
quarterly_data=[]
for i in range(int(len(list_of_DFs)/3)):
    quarterly_data.append(pd.concat(list_of_DFs[i*3:i*3+3]))
    if i%500==0:
        print(i)
        
for i in range(int(len(list_of_DFs2)/3)):
    quarterly_data.append(pd.concat(list_of_DFs2[i*3:i*3+3]))
    if i%500==0:
        print(i)

0
500
1000
1500
2000
2500
3000
3500
0
500
1000
1500
2000
2500
3000
3500

In [14]:
''' Making lists of quarterly dataframes, for convenience using copy of the original dataframe 
in order to have more recent reference ''' 
first_q=[x.copy(deep=True) for x in quarterly_data[::4]]
second_q=[x.copy(deep=True) for x in quarterly_data[1::4]]
third_q=[x.copy(deep=True) for x in quarterly_data[2::4]]
fourth_q=[x.copy(deep=True) for x in quarterly_data[3::4]]

## Transformation of the strings into floats and NaNs; for this purpose we use function "trans" together with function "applied_trans", which uses "apply" method to apply "trans" function to 5th-10th columns of each table in a quarter.

In [9]:
import re

In [10]:
def trans(item):
    y=item.split(".")
    y2=[x.split("-") for x in y]
    y=["-".join([re.sub("[^0-9]"," ",x)  for x in a]) for a in y2]
    z=".".join([x  for x in y])
    try:
        item=float(z)
    except:
        item=np.NaN
    return item

In [15]:
def applied_trans(quarter):
    for t in range(len(quarter)):
        if t%500==0:
            print(t)
        for i in range(4,10):
            quarter[t].iloc[:,i]=quarter[t].iloc[:,i].apply(trans)

In [16]:
'''  Converting strings to numbers where needed  '''
applied_trans(first_q)

0
500
1000
1500

In [17]:
'''  Converting strings to numbers where needed  '''
applied_trans(second_q)
applied_trans(third_q)
applied_trans(fourth_q)

0
500
1000
1500
0
500
1000
1500
0
500
1000
1500

In [18]:
'''     Exporting quarterly dataframes to the csv files        '''
qs_paths=['d:\moje_dokumenty\Desktop\IES\semester 11\Python\project\First_q\ '+str(10000+A)+".csv" for A in range(len(first_q))]
for i in range(len(first_q)):
    first_q[i].to_csv(qs_paths[i], index = None, header=True)

In [19]:
'''     Exporting quarterly dataframes to the csv files        '''
qs_paths2=['d:\moje_dokumenty\Desktop\IES\semester 11\Python\project\second_q\ '+str(10000+A)+".csv" for A in range(len(second_q))]
for i in range(len(second_q)):
    second_q[i].to_csv(qs_paths2[i], index = None, header=True)

In [20]:
'''     Exporting quarterly dataframes to the csv files        '''
qs_paths3=['d:\moje_dokumenty\Desktop\IES\semester 11\Python\project\Third_q\ '+str(10000+A)+".csv" for A in range(len(third_q))]
for i in range(len(third_q)):
    third_q[i].to_csv(qs_paths3[i], index = None, header=True)

In [21]:
'''     Exporting quarterly dataframes to the csv files        '''
qs_paths4=['d:\moje_dokumenty\Desktop\IES\semester 11\Python\project\Fourth_q\ '+str(10000+A)+".csv" for A in range(len(fourth_q))]
for i in range(len(fourth_q)):
    fourth_q[i].to_csv(qs_paths4[i], index = None, header=True)

In [22]:
first_q[310]

,city,year,month,Giorno,T Media,T min,T max,Precip.,Umidit√†,Vento Max
0,Grosseto,2015,Gennaio,1,4.0,1.0,9.0,NaN,36.0,56.0
1,Grosseto,2015,Gennaio,2,6.0,1.0,14.0,NaN,62.0,15.0
2,Grosseto,2015,Gennaio,3,7.0,2.0,14.0,NaN,79.0,19.0
3,Grosseto,2015,Gennaio,4,8.0,4.0,15.0,NaN,85.0,9.0
4,Grosseto,2015,Gennaio,5,6.0,1.0,14.0,NaN,45.0,24.0
5,Grosseto,2015,Gennaio,6,5.0,1.0,12.0,NaN,78.0,15.0
6,Grosseto,2015,Gennaio,7,8.0,4.0,14.0,NaN,81.0,15.0
7,Grosseto,2015,Gennaio,8,8.0,4.0,12.0,NaN,84.0,15.0
8,Grosseto,2015,Gennaio,9,8.0,3.0,14.0,NaN,80.0,13.0
9,Grosseto,2015,Gennaio,10,7.0,3.0,13.0,NaN,83.0,13.0
10,Grosseto,2015,Gennaio,11,9.0,4.0,15.0,NaN,81.0,30.0
11,Grosseto,2015,Gennaio,12,7.0,1.0,16.0,NaN,53.0,17.0
12,Grosseto,2015,Gennaio,13,7.0,0.0,14.0,NaN,74.0,22.0
13,Grosseto,2015,Gennaio,14,9.0,5.0,14.0,NaN,80.0,13.0
14,Grosseto,2015,Gennaio,15,7.0,1.0,14.0,NaN,81.0,24.0
15,Grosseto,2015,Gennaio,16,11.0,4.0,14.0,NaN,79.0,37.0
16,Grosseto,2015,Gennaio,17,12.0,6.0,15.0,NaN,71.0,39.0
17,Grosseto,2015,Gennaio,18,8.0,4.0,14.0,NaN,72.0,22.0
18,Grosseto,2015,Gennaio,19,6.0,0.0,13.0,NaN,71.0,11.0
19,Grosseto,2015,Gennaio,20,7.0,3.0,11.0,NaN,77.0,19.0
20,Grosseto,2015,Gennaio,21,8.0,5.0,10.0,NaN,80.0,28.0
21,Grosseto,2015,Gennaio,22,8.0,6.0,12.0,NaN,77.0,20.0
22,Grosseto,2015,Gennaio,23,9.0,4.0,12.0,NaN,58.0,35.0
23,Grosseto,2015,Gennaio,24,10.0,4.0,13.0,NaN,43.0,41.0
24,Grosseto,2015,Gennaio,25,8.0,6.0,10.0,NaN,43.0,43.0
25,Grosseto,2015,Gennaio,26,7.0,2.0,10.0,NaN,37.0,50.0
26,Grosseto,2015,Gennaio,27,3.0,-2.0,10.0,NaN,58.0,20.0
27,Grosseto,2015,Gennaio,28,4.0,-2.0,10.0,NaN,41.0,35.0
28,Grosseto,2015,Gennaio,29,5.0,-1.0,10.0,NaN,70.0,43.0
29,Grosseto,2015,Gennaio,30,10.0,5.0,13.0,NaN,56.0,69.0
...,...,...,...,...,...,...,...,...,...,...
1,Grosseto,2015,Marzo,2,13.0,11.0,17.0,NaN,81.0,26.0
2,Grosseto,2015,Marzo,3,13.0,9.0,19.0,NaN,58.0,26.0
3,Grosseto,2015,Marzo,4,9.0,4.0,14.0,NaN,84.0,19.0
4,Grosseto,2015,Marzo,5,8.0,6.0,9.0,NaN,45.0,76.0
5,Grosseto,2015,Marzo,6,8.0,6.0,11.0,NaN,23.0,61.0
6,Grosseto,2015,Marzo,7,8.0,3.0,12.0,NaN,24.0,43.0
7,Grosseto,2015,Marzo,8,9.0,5.0,13.0,NaN,31.0,46.0
8,Grosseto,2015,Marzo,9,9.0,5.0,15.0,NaN,48.0,24.0
9,Grosseto,2015,Marzo,10,9.0,2.0,16.0,NaN,66.0,20.0
10,Grosseto,2015,Marzo,11,10.0,2.0,17.0,NaN,79.0,20.0
11,Grosseto,2015,Marzo,12,10.0,6.0,14.0,NaN,43.0,41.0
12,Grosseto,2015,Marzo,13,8.0,1.0,15.0,NaN,48.0,19.0
13,Grosseto,2015,Marzo,14,9.0,3.0,16.0,NaN,67.0,19.0
14,Grosseto,2015,Marzo,15,10.0,8.0,12.0,NaN,73.0,32.0
15,Grosseto,2015,Marzo,16,10.0,9.0,12.0,NaN,82.0,20.0
16,Grosseto,2015,Marzo,17,12.0,10.0,14.0,NaN,78.0,15.0
17,Grosseto,2015,Marzo,18,11.0,7.0,17.0,NaN,59.0,11.0
18,Grosseto,2015,Marzo,19,10.0,4.0,16.0,NaN,72.0,13.0
19,Grosseto,2015,Marzo,20,10.0,5.0,15.0,NaN,73.0,17.0
20,Grosseto,2015,Marzo,21,9.0,5.0,13.0,NaN,73.0,17.0
21,Grosseto,2015,Marzo,22,11.0,8.0,14.0,NaN,54.0,28.0
22,Grosseto,2015,Marzo,23,13.0,9.0,17.0,NaN,57.0,24.0
23,Grosseto,2015,Marzo,24,13.0,8.0,17.0,NaN,74.0,26.0
24,Grosseto,2015,Marzo,25,12.0,11.0,14.0,NaN,79.0,48.0
25,Grosseto,2015,Marzo,26,13.0,9.0,16.0,NaN,75.0,30.0
26,Grosseto,2015,Marzo,27,11.0,8.0,14.0,NaN,70.0,28.0
27,Grosseto,2015,Marzo,28,12.0,7.0,19.0,NaN,38.0,32.0
28,Grosseto,2015,Marzo,29,10.0,3.0,17.0,NaN,63.0,15.0
29,Grosseto,2015,Marzo,30,14.0,8.0,19.0,NaN,78.0,15.0
30,Grosseto,2015,Marzo,31,14.0,8.0,21.0,NaN,77.0,20.0

In [23]:
second_q[10]

,city,year,month,Giorno,T Media,T min,T max,Precip.,Umidit√†,Vento Max
0,Bari,1995,Aprile,1,7.6,4.3,10.0,NaN,53.0,35.2
1,Bari,1995,Aprile,2,10.4,4.7,16.0,NaN,63.0,16.5
2,Bari,1995,Aprile,3,13.5,5.2,19.7,NaN,68.0,14.8
3,Bari,1995,Aprile,4,15.4,7.9,20.5,NaN,60.0,16.5
4,Bari,1995,Aprile,5,12.1,8.1,16.9,NaN,84.0,16.5
5,Bari,1995,Aprile,6,10.2,5.0,13.7,NaN,90.0,14.8
6,Bari,1995,Aprile,7,11.7,8.0,14.9,NaN,86.0,20.6
7,Bari,1995,Aprile,8,13.7,6.8,21.2,NaN,73.0,31.3
8,Bari,1995,Aprile,9,10.2,8.8,12.3,7.0,51.0,38.9
9,Bari,1995,Aprile,10,9.1,5.0,12.0,NaN,49.0,24.1
10,Bari,1995,Aprile,11,9.9,4.3,15.9,NaN,65.0,16.5
11,Bari,1995,Aprile,12,10.2,7.0,12.6,NaN,66.0,33.5
12,Bari,1995,Aprile,13,9.7,5.4,14.2,NaN,70.0,24.1
13,Bari,1995,Aprile,14,7.2,5.0,11.0,1.0,82.0,27.8
14,Bari,1995,Aprile,15,9.2,5.0,13.9,1.0,81.0,24.1
15,Bari,1995,Aprile,16,8.8,5.0,15.9,7.0,76.0,18.3
16,Bari,1995,Aprile,17,10.2,6.5,15.0,NaN,76.0,27.8
17,Bari,1995,Aprile,18,12.9,5.7,18.0,NaN,55.0,20.6
18,Bari,1995,Aprile,19,13.9,4.3,20.5,NaN,65.0,25.9
19,Bari,1995,Aprile,20,14.3,7.0,21.1,NaN,76.0,20.6
20,Bari,1995,Aprile,21,16.0,9.8,23.5,NaN,64.0,20.6
21,Bari,1995,Aprile,22,15.6,9.6,24.0,NaN,54.0,27.8
22,Bari,1995,Aprile,23,16.2,13.0,25.2,NaN,62.0,20.6
23,Bari,1995,Aprile,24,15.7,12.0,23.0,1.0,75.0,25.9
24,Bari,1995,Aprile,25,12.1,7.0,15.6,7.0,80.0,13.0
25,Bari,1995,Aprile,26,13.3,8.2,18.9,5.0,71.0,29.4
26,Bari,1995,Aprile,27,14.9,9.0,20.1,NaN,61.0,25.9
27,Bari,1995,Aprile,28,13.6,5.8,18.5,NaN,74.0,24.1
28,Bari,1995,Aprile,29,14.5,8.9,18.0,NaN,78.0,16.5
29,Bari,1995,Aprile,30,16.9,8.8,20.5,NaN,61.0,18.3
...,...,...,...,...,...,...,...,...,...,...
0,Bari,1995,Giugno,1,18.2,15.0,24.3,1.0,89.0,27.8
1,Bari,1995,Giugno,2,18.5,14.0,23.2,2.0,72.0,14.8
2,Bari,1995,Giugno,3,19.2,12.8,24.1,NaN,66.0,16.5
3,Bari,1995,Giugno,4,20.1,14.8,24.5,NaN,74.0,20.6
4,Bari,1995,Giugno,5,20.1,13.3,24.8,NaN,74.0,22.2
5,Bari,1995,Giugno,6,22.1,14.9,28.2,NaN,53.0,24.1
6,Bari,1995,Giugno,7,19.2,13.0,23.7,NaN,67.0,18.3
7,Bari,1995,Giugno,8,19.8,12.8,25.2,1.0,68.0,16.5
8,Bari,1995,Giugno,9,21.6,13.5,26.9,NaN,65.0,29.4
9,Bari,1995,Giugno,10,21.8,14.8,27.4,NaN,73.0,25.9
10,Bari,1995,Giugno,11,23.4,16.8,29.5,7.0,74.0,25.9
11,Bari,1995,Giugno,12,22.1,18.9,28.5,26.0,87.0,27.8
12,Bari,1995,Giugno,13,20.9,16.0,26.5,NaN,75.0,16.5
13,Bari,1995,Giugno,14,19.7,14.6,24.1,NaN,78.0,22.2
14,Bari,1995,Giugno,15,21.3,16.2,26.1,NaN,58.0,14.8
15,Bari,1995,Giugno,16,21.0,15.0,26.5,NaN,76.0,16.5
16,Bari,1995,Giugno,17,20.7,16.6,25.7,1.0,80.0,18.3
17,Bari,1995,Giugno,18,20.6,15.3,25.8,NaN,67.0,16.5
18,Bari,1995,Giugno,19,21.4,15.7,25.9,NaN,72.0,20.6
19,Bari,1995,Giugno,20,22.6,17.0,27.1,NaN,69.0,18.3
20,Bari,1995,Giugno,21,24.1,16.2,29.2,NaN,53.0,16.5
21,Bari,1995,Giugno,22,25.7,18.5,30.5,NaN,54.0,18.3
22,Bari,1995,Giugno,23,25.9,19.6,31.3,NaN,52.0,20.6
23,Bari,1995,Giugno,24,24.7,18.1,33.0,NaN,63.0,24.1
24,Bari,1995,Giugno,25,20.0,17.0,24.1,NaN,74.0,20.6
25,Bari,1995,Giugno,26,20.1,15.2,24.0,NaN,76.0,16.5
26,Bari,1995,Giugno,27,20.8,15.0,25.9,NaN,75.0,22.2
27,Bari,1995,Giugno,28,22.6,19.0,27.5,NaN,69.0,24.1
28,Bari,1995,Giugno,29,23.0,19.2,27.8,NaN,74.0,18.3
29,Bari,1995,Giugno,30,22.8,18.0,27.0,NaN,73.0,18.3

In [24]:
third_q[3]

,city,year,month,Giorno,T Media,T min,T max,Precip.,Umidit√†,Vento Max
0,Bari,1988,Luglio,1,26.8,15.8,33.0,NaN,46.0,29.4
1,Bari,1988,Luglio,2,26.2,21.0,32.0,NaN,57.0,18.3
2,Bari,1988,Luglio,3,25.4,19.6,30.0,NaN,48.0,18.3
3,Bari,1988,Luglio,4,25.8,15.2,32.0,NaN,42.0,18.3
4,Bari,1988,Luglio,5,29.9,18.2,38.0,NaN,35.0,22.2
5,Bari,1988,Luglio,6,32.9,23.0,39.0,NaN,27.0,11.1
6,Bari,1988,Luglio,7,28.2,22.0,33.0,NaN,48.0,11.1
7,Bari,1988,Luglio,8,28.1,23.0,36.0,NaN,56.0,18.3
8,Bari,1988,Luglio,9,26.2,20.0,32.0,NaN,50.0,22.2
9,Bari,1988,Luglio,10,25.2,20.9,29.0,NaN,62.0,25.9
10,Bari,1988,Luglio,11,24.9,20.8,28.2,NaN,57.0,18.3
11,Bari,1988,Luglio,12,24.7,20.0,29.0,NaN,63.0,14.8
12,Bari,1988,Luglio,13,25.3,17.8,30.0,NaN,60.0,18.3
13,Bari,1988,Luglio,14,28.6,19.6,35.0,NaN,53.0,22.2
14,Bari,1988,Luglio,15,28.4,21.0,35.4,NaN,49.0,29.4
15,Bari,1988,Luglio,16,24.3,21.5,28.0,NaN,66.0,29.4
16,Bari,1988,Luglio,17,22.9,19.2,26.2,NaN,70.0,27.8
17,Bari,1988,Luglio,18,23.4,18.0,28.0,NaN,58.0,24.1
18,Bari,1988,Luglio,19,23.4,17.0,28.0,NaN,64.0,22.2
19,Bari,1988,Luglio,20,24.0,18.0,36.0,NaN,67.0,22.2
20,Bari,1988,Luglio,21,23.8,16.8,29.0,NaN,64.0,22.2
21,Bari,1988,Luglio,22,24.7,17.2,30.0,NaN,52.0,14.8
22,Bari,1988,Luglio,23,24.9,17.8,31.0,NaN,65.0,13.0
23,Bari,1988,Luglio,24,26.8,17.8,34.0,NaN,37.0,16.5
24,Bari,1988,Luglio,25,28.2,20.8,36.0,NaN,47.0,29.4
25,Bari,1988,Luglio,26,27.1,22.0,31.0,NaN,60.0,24.1
26,Bari,1988,Luglio,27,25.9,19.6,31.0,NaN,58.0,14.8
27,Bari,1988,Luglio,28,26.6,19.0,33.8,NaN,52.0,18.3
28,Bari,1988,Luglio,29,27.7,20.6,33.0,NaN,56.0,18.3
29,Bari,1988,Luglio,30,26.9,19.8,31.2,NaN,57.0,29.4
...,...,...,...,...,...,...,...,...,...,...
0,Bari,1988,Settembre,1,23.8,18.0,28.6,NaN,76.0,16.5
1,Bari,1988,Settembre,2,28.5,17.4,39.0,NaN,36.0,37.0
2,Bari,1988,Settembre,3,23.6,18.0,27.4,NaN,56.0,14.8
3,Bari,1988,Settembre,4,22.7,18.0,27.8,NaN,63.0,11.1
4,Bari,1988,Settembre,5,23.0,16.8,28.8,NaN,70.0,18.3
5,Bari,1988,Settembre,6,22.9,17.0,28.0,NaN,75.0,14.8
6,Bari,1988,Settembre,7,22.2,20.0,25.0,NaN,47.0,37.0
7,Bari,1988,Settembre,8,20.9,18.0,24.0,NaN,48.0,33.5
8,Bari,1988,Settembre,9,19.5,15.0,23.8,NaN,61.0,16.5
9,Bari,1988,Settembre,10,19.6,15.0,25.2,NaN,59.0,16.5
10,Bari,1988,Settembre,11,19.4,12.8,25.6,NaN,57.0,13.0
11,Bari,1988,Settembre,12,20.3,13.6,26.4,NaN,52.0,18.3
12,Bari,1988,Settembre,13,22.3,14.0,27.0,NaN,62.0,22.2
13,Bari,1988,Settembre,14,23.3,19.0,29.0,NaN,70.0,18.3
14,Bari,1988,Settembre,15,19.7,16.0,23.0,7.0,85.0,38.9
15,Bari,1988,Settembre,16,18.0,13.2,21.0,NaN,74.0,14.8
16,Bari,1988,Settembre,17,15.7,14.0,19.0,65.0,87.0,33.5
17,Bari,1988,Settembre,18,16.2,12.8,20.4,NaN,75.0,14.8
18,Bari,1988,Settembre,19,17.3,13.0,22.0,NaN,78.0,13.0
19,Bari,1988,Settembre,20,17.4,13.0,22.0,NaN,75.0,14.8
20,Bari,1988,Settembre,21,17.0,13.0,21.0,NaN,81.0,13.0
21,Bari,1988,Settembre,22,17.7,14.6,21.2,9.0,85.0,18.3
22,Bari,1988,Settembre,23,18.6,14.0,23.5,NaN,74.0,9.4
23,Bari,1988,Settembre,24,20.1,15.0,24.4,NaN,69.0,11.1
24,Bari,1988,Settembre,25,19.7,14.0,24.8,NaN,78.0,13.0
25,Bari,1988,Settembre,26,19.5,16.0,25.0,NaN,79.0,14.8
26,Bari,1988,Settembre,27,19.6,15.0,25.0,NaN,71.0,14.8
27,Bari,1988,Settembre,28,18.4,14.0,24.8,NaN,79.0,9.4
28,Bari,1988,Settembre,29,18.6,13.0,25.0,NaN,79.0,13.0
29,Bari,1988,Settembre,30,19.4,13.5,26.4,NaN,72.0,18.3

In [25]:
fourth_q[51]

,city,year,month,Giorno,T Media,T min,T max,Precip.,Umidit√†,Vento Max
0,Bologna,2001,Ottobre,1,18.4,13.0,24.0,NaN,76.0,11.1
1,Bologna,2001,Ottobre,2,20.0,17.0,24.2,NaN,72.0,13.0
2,Bologna,2001,Ottobre,3,18.9,14.0,24.0,NaN,80.0,11.1
3,Bologna,2001,Ottobre,4,19.1,14.4,25.0,NaN,87.0,24.1
4,Bologna,2001,Ottobre,5,19.3,14.0,23.4,NaN,81.0,11.1
5,Bologna,2001,Ottobre,6,19.9,15.9,24.0,NaN,87.0,18.3
6,Bologna,2001,Ottobre,7,21.5,18.8,26.9,NaN,88.0,18.3
7,Bologna,2001,Ottobre,8,20.9,16.0,26.1,NaN,79.0,14.8
8,Bologna,2001,Ottobre,9,19.7,15.0,25.0,NaN,68.0,9.4
9,Bologna,2001,Ottobre,10,17.9,16.0,21.7,NaN,89.0,14.8
10,Bologna,2001,Ottobre,11,18.9,14.5,24.7,NaN,75.0,13.0
11,Bologna,2001,Ottobre,12,17.7,13.7,25.8,NaN,78.0,13.0
12,Bologna,2001,Ottobre,13,17.9,13.4,24.9,NaN,74.0,14.8
13,Bologna,2001,Ottobre,14,17.8,12.5,24.0,NaN,72.0,14.8
14,Bologna,2001,Ottobre,15,16.8,12.4,23.1,NaN,75.0,11.1
15,Bologna,2001,Ottobre,16,17.4,13.0,22.7,NaN,75.0,11.1
16,Bologna,2001,Ottobre,17,16.5,12.0,22.0,NaN,79.0,11.1
17,Bologna,2001,Ottobre,18,16.1,11.0,22.0,NaN,77.0,11.1
18,Bologna,2001,Ottobre,19,16.2,12.0,22.0,NaN,83.0,11.1
19,Bologna,2001,Ottobre,20,17.8,12.5,23.0,NaN,83.0,18.3
20,Bologna,2001,Ottobre,21,18.2,12.8,24.6,22.0,66.0,27.8
21,Bologna,2001,Ottobre,22,15.6,11.4,20.0,NaN,83.0,11.1
22,Bologna,2001,Ottobre,23,16.4,11.0,20.4,NaN,70.0,13.0
23,Bologna,2001,Ottobre,24,15.3,13.0,19.0,8.0,91.0,13.0
24,Bologna,2001,Ottobre,25,14.3,10.7,19.2,NaN,84.0,11.1
25,Bologna,2001,Ottobre,26,14.2,11.0,19.5,NaN,79.0,9.4
26,Bologna,2001,Ottobre,27,13.4,9.7,18.0,NaN,84.0,11.1
27,Bologna,2001,Ottobre,28,13.5,11.9,16.0,NaN,92.0,7.6
28,Bologna,2001,Ottobre,29,12.6,10.0,16.4,NaN,89.0,7.6
29,Bologna,2001,Ottobre,30,12.6,9.7,17.0,NaN,91.0,9.4
...,...,...,...,...,...,...,...,...,...,...
1,Bologna,2001,Dicembre,2,5.9,3.0,9.0,NaN,87.0,11.1
2,Bologna,2001,Dicembre,3,4.9,1.0,10.0,NaN,84.0,13.0
3,Bologna,2001,Dicembre,4,4.2,0.7,7.3,NaN,88.0,11.1
4,Bologna,2001,Dicembre,5,6.9,4.0,11.9,NaN,81.0,7.6
5,Bologna,2001,Dicembre,6,5.5,0.6,11.0,NaN,83.0,13.0
6,Bologna,2001,Dicembre,7,5.4,2.0,10.5,NaN,74.0,16.5
7,Bologna,2001,Dicembre,8,3.0,-2.2,8.2,NaN,74.0,20.6
8,Bologna,2001,Dicembre,9,1.2,-2.8,7.5,NaN,69.0,22.2
9,Bologna,2001,Dicembre,10,0.4,-3.0,5.1,NaN,66.0,13.0
10,Bologna,2001,Dicembre,11,0.4,-4.1,4.7,NaN,71.0,11.1
11,Bologna,2001,Dicembre,12,0.6,-2.5,5.3,NaN,80.0,13.0
12,Bologna,2001,Dicembre,13,-0.6,-3.0,3.6,1.0,81.0,37.0
13,Bologna,2001,Dicembre,14,-0.9,-3.0,1.0,1.0,68.0,31.3
14,Bologna,2001,Dicembre,15,-1.0,-3.1,1.0,NaN,58.0,16.5
15,Bologna,2001,Dicembre,16,-1.1,-4.0,4.0,NaN,65.0,18.3
16,Bologna,2001,Dicembre,17,-1.8,-6.0,5.2,NaN,64.0,13.0
17,Bologna,2001,Dicembre,18,-1.6,-5.0,4.7,NaN,63.0,11.1
18,Bologna,2001,Dicembre,19,-1.1,-5.3,4.0,NaN,70.0,13.0
19,Bologna,2001,Dicembre,20,0.2,-4.0,4.5,NaN,77.0,NaN
20,Bologna,2001,Dicembre,21,0.6,-2.0,5.2,NaN,85.0,11.1
21,Bologna,2001,Dicembre,22,0.5,-3.6,5.4,NaN,86.0,9.4
22,Bologna,2001,Dicembre,23,-0.2,-3.3,3.2,NaN,88.0,9.4
23,Bologna,2001,Dicembre,24,-1.3,-4.0,3.0,NaN,68.0,13.0
24,Bologna,2001,Dicembre,25,-0.3,-4.8,7.2,NaN,50.0,14.8
25,Bologna,2001,Dicembre,26,-1.2,-5.0,1.1,1.0,86.0,13.0
26,Bologna,2001,Dicembre,27,1.6,-2.9,6.3,3.0,48.0,14.8
27,Bologna,2001,Dicembre,28,1.9,-3.0,8.6,NaN,47.0,14.8
28,Bologna,2001,Dicembre,29,-0.7,-4.0,4.0,NaN,78.0,5.4
29,Bologna,2001,Dicembre,30,3.3,-2.2,9.2,NaN,78.0,9.4
30,Bologna,2001,Dicembre,31,1.8,-1.0,5.0,37.0,86.0,13.0